server.port=8080
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database

jwt.secret=this-is-a-very-long-secret-key-for-hs256-must-be-at-least-256-bits
jwt.expiration-ms=3600000
